@startuml overview

'========================================== BOILER PLATE ==========================================

class Screen {}
Screen <-- Renderer

'========================================== RENDERER ==========================================

class Renderer {
    +setScene()
    -DrawCall()
}
class BitMap3D {
    -int width
    -int height
    -byte[] bitmap
    -double[][] zBuffer
    +setPixel()
    +DrawLine()
}
class GeometryProcessor {}
class Rasterizer {}
class PixelProcesser {}

Renderer *-- GeometryProcessor
Renderer *-- Rasterizer
Renderer *-- PixelProcesser
Renderer *-- BitMap3D
Renderer o-- Scene

GeometryProcessor <-- VertexShader
GeometryProcessor <-- Tesselator

'========================================== SCENE ==========================================
class Scene {
    -Object3D[] objects
    +addObject()
}
class Object3D {
    -Matrix scale
    -Matrix translation
    -double[] vertices
    -double[] indeces
    -double[] colours
    +setScale()
    +setTranslation()
    +getData()
}
class Triangle {
    -int[] vertexIndeces
    -Colour colour 
}
interface Light {
    -Vector position
    -Vector Direction
    -Colour colour
    -int intensity
}
class PointLight {}
class SpotLight {}
class SunLight {}
class AreaLight {}

Scene o-- Object3D
Scene o-- Light
Object3D <-- Triangle
Light <-- PointLight
Light <-- SpotLight
Light <-- SunLight
Light <-- AreaLight

'========================================== UTILITY ==========================================
class Matrix {

}
class Vector {

}

@enduml